sudo: required
dist: xenial
os:
- linux
language: cpp
cache:
- ccache
env:
  global:
  - CCACHE_MAXSIZE: 1G
  - secure: r5SNhSkxjKOAM2L+SNucQWowy2n4OREFAA0POPhUAQ0suis9SUSVCnW3lt/OBr1chhMzr9QJViQMdwqhiPMWWb6QS3C46FtOLQQBrLIy9bSs/HOo0jQLG8jHxWcifiUNWuD8E4QjNb7jn6gU//zRVxWx4lnJ1U6EfQn6dx1BoFvFhkQTdgBULZx5Tqt83DtpS4JjFIJFelghw8jE/vAzDB5Vct3p+Ua0lJgpeS59p61hv/j6rTrsl1sYaKEm6I5aifvmBhOo0dlcP+MYtfr5yVdmpw2VTh4fMHsI8wBgh7zeHb2Iz5rB+CZOwZfeETlUDJWwvMIzF1LxvpcD5BWWu+3F0ybo4TpxHibCtI632peIUc49IxSLC9JOA8EoQgpX0thfB3qfMh4v9hX9K0OXl6j0gSCVjVF23aq7hDcWITy+9fXbO0Jeq4eX7dQOZp/GoICLMQwnu/o7yswRSCkTvPf9rIbxOCxH9xgahZyz7hI4OoEM7eAg0/YpVgp7C7XBXv/MrMCjP2Ad4phlaMBV9x/zKWUvxnGq3x6OoZcjC8r+0BcfgIS6aUalVkg2el75sPfADqHX1xXhUc2i1GycyGJwAeGgxQ7/zDmEqHxRl/5syWft2F/hpAzlAAT9OdsUY15VTyOnsYdjdsLEGJVnmHbDdpTRCnzg2LBtNq598lg=
before_install:
install:
before_script:
script:
- "/bin/bash quicksync.sh"
after_script:
- echo "Done"
notifications:
  email:
    recipients:
    - info@nebl.io
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
- provider: s3
  endpoint: https://ams3.digitaloceanspaces.com
  access_key_id: BVBRJD657FTIX7SNYNL2
  secret_access_key:
    secure: OjWjkOgJ2PXQ+zMGBGR/qR3ap6yrurQDi9fAhcZ1bQVc7S15SS8N3zvnFQ+3zCJFUy34rPzt9orzOVAae2JzRzW5lpAXNinAS5R94pYlyAOdL7/QAPjtvkn4nbaA6PBmoQzrhNxAG2sNe5CCA/RnsurUuvgwjLKmmlOPrz/jPGLPsI/PXKZINXlOcPYhfaaM8jvhWFB+sRhh7V6nc+P5qd1rWuhfqkjKyXjlM5XBDSgf8SX2GiPZ8mpwIqTHNNy45VemOPfy26o5cx3jCpVhEctHtdR6h2ve8XtbTMvCRWwnNBHoWgQyPI3llZW2vok+2LX+wNQcAMDp/HWOw+iSB+LKGNDp1+4aFxO6atbzZi+J9ZStQvplSsckaHRw/KCqokgLeM3AMPKfqh0GwaAYRZYd3S4So7vU2EIoTR20GAypbafc35SqWezteGj2fa05JLNjVf5Z3FejjEuo0aB/ujGS20yQz3kMSA6zMozGgwVHTnbeEFXLpbK2sFT5fraDjSAloz5iYXdgeVdUG+JvzGxnJ3R2C7SmoxtPzTasMvbWLejcafpBZm+JqrGKvU7At4oBIbzo3/F5eF781mX6G0C7XqBKGLV1ktr362qGAP5UMcz5jXWFX8vVu72Yfrycq+oJgVpx1oXbSQbbLXphT8lP6GOeVhCrUMxLiRh6NV0=
  bucket: quicksync
  local-dir: txlmdb
  upload-dir: txlmdb
  skip_cleanup: true
  detect_encoding: true
  acl: public_read
  overwrite: true
  on:
    repo: NeblioTeam/neblio-quicksync
    all_branches: true
- provider: s3
  endpoint: https://sfo2.digitaloceanspaces.com
  access_key_id: BVBRJD657FTIX7SNYNL2
  secret_access_key:
    secure: OjWjkOgJ2PXQ+zMGBGR/qR3ap6yrurQDi9fAhcZ1bQVc7S15SS8N3zvnFQ+3zCJFUy34rPzt9orzOVAae2JzRzW5lpAXNinAS5R94pYlyAOdL7/QAPjtvkn4nbaA6PBmoQzrhNxAG2sNe5CCA/RnsurUuvgwjLKmmlOPrz/jPGLPsI/PXKZINXlOcPYhfaaM8jvhWFB+sRhh7V6nc+P5qd1rWuhfqkjKyXjlM5XBDSgf8SX2GiPZ8mpwIqTHNNy45VemOPfy26o5cx3jCpVhEctHtdR6h2ve8XtbTMvCRWwnNBHoWgQyPI3llZW2vok+2LX+wNQcAMDp/HWOw+iSB+LKGNDp1+4aFxO6atbzZi+J9ZStQvplSsckaHRw/KCqokgLeM3AMPKfqh0GwaAYRZYd3S4So7vU2EIoTR20GAypbafc35SqWezteGj2fa05JLNjVf5Z3FejjEuo0aB/ujGS20yQz3kMSA6zMozGgwVHTnbeEFXLpbK2sFT5fraDjSAloz5iYXdgeVdUG+JvzGxnJ3R2C7SmoxtPzTasMvbWLejcafpBZm+JqrGKvU7At4oBIbzo3/F5eF781mX6G0C7XqBKGLV1ktr362qGAP5UMcz5jXWFX8vVu72Yfrycq+oJgVpx1oXbSQbbLXphT8lP6GOeVhCrUMxLiRh6NV0=
  bucket: quicksync-backup
  local-dir: txlmdb
  upload-dir: txlmdb
  skip_cleanup: true
  detect_encoding: true
  acl: public_read
  overwrite: true
  on:
    repo: NeblioTeam/neblio-quicksync
    all_branches: true
after_script:
- git config --global user.email "info@nebl.io"
- git config --global user.name "NeblioTeam"
- git checkout master
- python update_json.py
- git add download.json
- git commit -m "Daily update of download.json for QuickSync"
- git push https://${GHAT}@github.com/NeblioTeam/neblio-quicksync master > /dev/null 2>&1
