sudo: required
dist: xenial
os:
- linux
language: cpp
cache:
- ccache
env:
  global:
  - CCACHE_MAXSIZE: 1G
  - secure: "r5SNhSkxjKOAM2L+SNucQWowy2n4OREFAA0POPhUAQ0suis9SUSVCnW3lt/OBr1chhMzr9QJViQMdwqhiPMWWb6QS3C46FtOLQQBrLIy9bSs/HOo0jQLG8jHxWcifiUNWuD8E4QjNb7jn6gU//zRVxWx4lnJ1U6EfQn6dx1BoFvFhkQTdgBULZx5Tqt83DtpS4JjFIJFelghw8jE/vAzDB5Vct3p+Ua0lJgpeS59p61hv/j6rTrsl1sYaKEm6I5aifvmBhOo0dlcP+MYtfr5yVdmpw2VTh4fMHsI8wBgh7zeHb2Iz5rB+CZOwZfeETlUDJWwvMIzF1LxvpcD5BWWu+3F0ybo4TpxHibCtI632peIUc49IxSLC9JOA8EoQgpX0thfB3qfMh4v9hX9K0OXl6j0gSCVjVF23aq7hDcWITy+9fXbO0Jeq4eX7dQOZp/GoICLMQwnu/o7yswRSCkTvPf9rIbxOCxH9xgahZyz7hI4OoEM7eAg0/YpVgp7C7XBXv/MrMCjP2Ad4phlaMBV9x/zKWUvxnGq3x6OoZcjC8r+0BcfgIS6aUalVkg2el75sPfADqHX1xXhUc2i1GycyGJwAeGgxQ7/zDmEqHxRl/5syWft2F/hpAzlAAT9OdsUY15VTyOnsYdjdsLEGJVnmHbDdpTRCnzg2LBtNq598lg="
before_install:
install:
before_script:
script:
- /bin/bash quicksync.sh

after_script:
- echo "Done"
notifications:
  email:
    recipients:
    - info@nebl.io
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
  - provider: s3
    endpoint: https://ams3.digitaloceanspaces.com
    access_key_id: 2VUF47CKX6AGTOKSGPBC
    secret_access_key:
      secure: DgrrcxBrf2mgfWN30ACSIgEhQJaIaWuJKO3/gAQR/1la434O5U+hnJ0nFzF431eogeBXwV5gdcsuIQaxcg2pB40orrQ1QEnwL8CQZfB0A9dyAr0YRFS9aWg4vF2UjvYkLF1iFaRjjpdxjLtdamlXG5Ea7jsxn4vLNRQm09SYoBLVXn7JYiLvyVsrtpaVR0E/hCl+U7rQVtkVSI5d0jUKUQimV7cgYhYGUsDnOQZcGdXHhQp7Hv0IQ8KSLdmH6At0DQiAmr6p0z6ToEn0uq2iZip6pPcz/VrnbUIPV8zJjlyyZ9I9MQ8h+V33iSeHCgOGXqIRH6E5IR3yfWUfvk6qUt3vVxU+wI0avceOC1wrV8qTqr6CJ8rvTnCMzHTuDtBK4lyNYregz+3Omj7zIKEiHt3lsyM1ClJixD0xJVuxNr2CRxgK4A53eHvRhZ+wjAPseVT06tfs3JaR0wxuO1QB5Xp4BUUwQF9jGnUu2GazIbJVkhFQMFmuwTDk8kwpVaQmVlkOMuYkThpxOf3vSMztKvtZ8lImFh7Ci8leQ8TQOxloZLPJwIvYadILjatX2k7btAKTkCawQSdmOZJh22c8M1aYxR/TxcnEyah43FhMyRQ/LNdWkvsWHFwpHHryLD8sEuZy2liotFFIgqfiaAFTF94Sm6F29DhHglh1SdGEznM=
    bucket: quicksync
    skip_cleanup: true
    detect_encoding: true
    local_dir: txlmdb
    upload-dir: txlmdb
    acl: public_read
    overwrite: true
    on:
      repo: NeblioTeam/neblio-quicksync
      all_branches: true
after_deploy:
- python update_json.py
- git add download.json
- git commit -m "Daily update of download.json for QuickSync"
- git push "https://${GHAT}@github.com/NeblioTeam/neblio-quicksync" master > /dev/null 2>&1