name: neblio-quicksync

on: [push,repository_dispatch]
#   schedule:
#     - cron:  '15 * * * *'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET1: 'quicksync'
  AWS_S3_ENDPOINT1: 'https://ams3.digitaloceanspaces.com'
  AWS_S3_BUCKET2: 'quicksync-backup'
  AWS_S3_ENDPOINT2: 'https://sfo2.digitaloceanspaces.com'

jobs:
  linux_daemon_build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: ccache
      uses: actions/cache@v1
      with:
        path: .ccache
        key: ${{ runner.OS }}--linux_daemon-${{ github.sha }}
        restore-keys: |
          ${{ runner.OS }}--linux_daemon-
    - name: Install Dependencies & Setup Environment
      run: |
        echo "::set-env name=BUILD_DIR::$(echo ${GITHUB_WORKSPACE})"
        echo "::set-env name=DEST_DIR::$(echo txlmdb/)$(echo ${GITHUB_SHA})"
        pip install awscli --upgrade --user
        sudo pip uninstall -y urllib3
        sudo pip install urllib3==1.22
        sudo pip install requests
    - name: Build nebliod for Linux & Sync
      run: |
        /bin/bash quicksync.sh
    - name: Upload Quicksync Files to AMS3
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET1 }}
        AWS_S3_ENDPOINT: ${{ env.AWS_S3_ENDPOINT1 }}
        SOURCE_DIR: txlmdb
    - name: Upload Quicksync Files to SFO2
      uses: jakejarvis/s3-sync-action@v0.5.0
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ env.AWS_S3_BUCKET2 }}
        AWS_S3_ENDPOINT: ${{ env.AWS_S3_ENDPOINT2 }}
        SOURCE_DIR: txlmdb
    - name: Verify Uploaded Files
      run: |
        python verify_deploy.py

